preload = ~/Pictures/Wallpapers/78552291_p0.png
preload = ~/Pictures/Wallpapers/88589772_p0.png

wallpaper = HDMI-A-1, contain:~/Pictures/Wallpapers/78552291_p0.png
wallpaper = DP-2, contain:~/Pictures/Wallpapers/88589772_p0.png
